create table mensagens(
    id numeric generated by default as identity,
    assunto varchar2(255),
    destinatario varchar2(255),
    remetente varchar2(255),
    conteudo varchar2(255),
    primary key(id)
);